Repository lion-packages/exceptions, pull requests merged in 2025-01, with the labels that each got.

#14 Standardization of PHPStan, PHP_CodeSniffer
  .github/workflows/php.yml
  .gitignore
  composer.json
  composer.lock
  phpunit.xml
  public/serialize-json.php
  src/LionExceptions/Serialize.php
  src/LionExceptions/Traits/ExceptionTrait.php
  test.sh
  tests/ExceptionTest.php
  tests/SerializeTest.php
  tests/Traits/ExceptionTraitTest.php
Labels: enhancement, dependencies

#13 GitHub Actions configuration updated
  .github/workflows/php.yml
Labels: continuous integration

#15 Documentation files have been relocated
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/README.md
Labels: documentation

#16 Update LICENSE
  LICENSE
Labels: documentation
