Repository lion-packages/exceptions, pull requests merged in 2025-03, with the labels that each got.

#18 Update PHPUnit v12
  composer.json
  phpunit.xml
Labels: dependencies

#19 Add cache in workflow
  .github/workflows/php.yml
Labels: continuous integration

#20 Added dependency-review in Github Actions
  .github/workflows/php.yml
Labels: continuous integration

#21 PHPLint is integrated
  .github/workflows/php.yml
  .gitignore
  composer.json
Labels: continuous integration, dependencies

#22 Added dependabot
  .github/dependabot.yml
Labels: continuous integration

#23 Infection is integrated
  .github/workflows/php.yml
  composer.json
  infection.json
Labels: continuous integration
