Repository lion-packages/exceptions, pull requests merged in 2025-04, with the labels that each got.

#24 Update README.md
  .github/README.md
Labels: documentation

#25 Update dependabot.yml
  .github/dependabot.yml
Labels: continuous integration

#26 Apply fixes from StyleCI
  src/LionExceptions/Serialize.php
Labels: standardization

#28 Adding a condition to run test coverage in Github Actions (Pull Request)
  .github/workflows/php.yml
Labels: continuous integration

#29 Define the execution time for Github Actions
  .github/workflows/php.yml
Labels: continuous integration

#30 Define the runtime for the Dependabot
  .github/dependabot.yml
Labels: continuous integration
